In [1]:
import torch
import src.models as mdls
import src.utils as utils
import torchvision.transforms as tf


In [2]:
model = mdls.InspectorGadjet()

In [ ]:
model_state_dict = torch.load('/Users/andreisuhov/Desktop/крутые веса /vgg4_27.pth', map_location=torch.device('cpu'))['model_state_dict']
model.load_state_dict(model_state_dict)
model.eval()

In [4]:
utils.cam_capture(0, model=model)

tensor([ 1.0840, 39.9569, 39.8858, 68.3675, 71.4305])
old [39.9569206237793, 39.88579559326172, 68.36747741699219, 71.43052673339844]
new [399, 224, 683, 401]
tensor([ 1.0842, 39.9633, 39.9333, 68.3893, 71.4848])
old [39.96334457397461, 39.93325424194336, 68.38934326171875, 71.48478698730469]
new [399, 224, 683, 402]
tensor([ 1.0842, 39.9637, 39.9340, 68.3901, 71.4858])
old [39.963680267333984, 39.93398666381836, 68.39009094238281, 71.48578643798828]
new [399, 224, 683, 402]
tensor([ 1.0842, 39.9637, 39.9342, 68.3902, 71.4861])
old [39.96373748779297, 39.93421936035156, 68.39016723632812, 71.48605346679688]
new [399, 224, 683, 402]
tensor([ 1.0842, 39.9633, 39.9346, 68.3899, 71.4866])
old [39.96334457397461, 39.93461608886719, 68.38987731933594, 71.48660278320312]
new [399, 224, 683, 402]
tensor([ 1.0842, 39.9635, 39.9347, 68.3903, 71.4870])
old [39.96345520019531, 39.934722900390625, 68.3902587890625, 71.4869613647461]
new [399, 224, 683, 402]
tensor([ 1.0842, 39.9628, 39.9349, 68.389

: 