In [1]:
import torch

import zipfile
from pathlib import Path

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch.nn as nn
from torchvision import models, transforms, datasets
from torch.utils.data import DataLoader, Dataset

from tqdm import tqdm
import datetime
import random
import cv2
import src.models as mdls
import src.dataloaders as dataloaders
import src.utils as utils
from numpy import inf
import torchvision
import torchvision.transforms as tf


In [2]:
model = mdls.get_pretrained_VGG16()

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


In [3]:
model_state_dict = torch.load('/Users/andreisuhov/Desktop/checkpoint_epoch_9.pth', map_location=torch.device('cpu'))['model_state_dict']
model.load_state_dict(model_state_dict)

<All keys matched successfully>

In [4]:
model.eval()

VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace=True)
    (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU(inplace=True)
    (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): ReLU(inplace=True)
    (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): ReLU(inplace=True)
    (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): ReLU(inplace=True)
    (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (15): ReLU(inplace=True)
    (16): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1

In [5]:
utils.cam_capture(0, model=model)

(720, 1280, 3)
[377, 141, 724, 380]
tensor([[ 0.4541, 37.1843, 24.8399, 71.2773, 66.5740]])
(720, 1280, 3)
[292, 27, 887, 425]
tensor([[ 0.2843, 28.8330,  4.7569, 87.3594, 74.5042]])
(720, 1280, 3)
[305, 27, 909, 431]
tensor([[ 0.3200, 30.0900,  4.8466, 89.5738, 75.5180]])
(720, 1280, 3)
[291, 24, 876, 414]
tensor([[ 0.3125, 28.6940,  4.2451, 86.2803, 72.6199]])
(720, 1280, 3)
[328, 35, 898, 417]
tensor([[ 0.3744, 32.3059,  6.2332, 88.4680, 73.0254]])
(720, 1280, 3)
[336, 34, 920, 425]
tensor([[ 0.3680, 33.1381,  6.0601, 90.6224, 74.4751]])
(720, 1280, 3)
[335, 33, 926, 430]
tensor([[ 0.3626, 32.9942,  5.7866, 91.2425, 75.4109]])
(720, 1280, 3)
[319, 27, 915, 429]
tensor([[ 0.3784, 31.4122,  4.7269, 90.1378, 75.1297]])
(720, 1280, 3)
[328, 30, 929, 436]
tensor([[ 0.3709, 32.3479,  5.2904, 91.5128, 76.3437]])
(720, 1280, 3)
[309, 25, 942, 451]
tensor([[ 0.3341, 30.4569,  4.3814, 92.7331, 79.0996]])
(720, 1280, 3)
[316, 25, 944, 450]
tensor([[ 0.3055, 31.1809,  4.5280, 92.9850, 78.7678]]